function [globalStatePREV, globalScalePREV, localStatePREV, localScalePREV] = ...
    horseshoePosteriorDraw2(shocks2, globalStatePREV, globalScalePREV, ~, localScalePREV, dim, s)
% HORSESHOEPOSTERIORDRAW2
% Gibbs updates for a horseshoe block using the Makalic-Schmidt
% inverse-gamma augmentation, with an additional fixed scale parameter s.
%
% This version assumes the input data are already standardized as
%   shocks.^2 ./ sigma.^2
% so sigma is NOT drawn and does not appear explicitly in the updates.
%
% INPUTS
%   shocks2 : squared shocks / squared coefficients divided by
%                       sigma^2, i.e. shocks.^2 ./ sigma.^2
%                       (NaNs are allowed and ignored in the sums)
%   globalStatePREV   : previous draw of global state, interpreted as
%                       \tilde{\tau}^2 in the parameterization
%                         tau = s * \tilde{tau}
%   globalScalePREV   : previous draw of auxiliary global scale variable xi
%   localScalePREV    : previous draw of auxiliary local scale variables nu
%   dim               : dimension over which to aggregate (default: 1)
%   s                 : fixed sparsity scale; tau = s * \tilde{tau}; see Piironen and Vehtari (2017) for details on choosing s
%                       (default: 1)
%
% OUTPUTS
%   globalStatePREV   : updated draw of \tilde{\tau}^2
%   globalScalePREV   : updated draw of xi
%   localStatePREV    : updated draw of local states lambda_t^2
%   localScalePREV    : updated draw of local auxiliary variables nu_t
%
% MODEL BLOCK
%   Conditional on the scales, the shrunk objects obey
%       shock_t / sigma ~ N(0, s^2 * \tilde{tau}^2 * lambda_t^2)
%
%   Hence the Makalic-Schmidt updates use the standardized quadratic term
%       shocks.^2 ./ sigma.^2
%   and rescale it by s^2 and the current global/local states.
%
% Elmar-style adaptation generated by ChatGPT, 09-Apr-2026.

%% prepare
if nargin < 6 || isempty(dim)
    dim = 1;
end
if nargin < 7 || isempty(s)
    s = 1;
end

T       = sum(~isnan(shocks2), dim);
Tp1half = (T + 1) .* .5;

igamrnd = @(alpha,beta) 1 ./ gamrnd(alpha, 1 ./ beta);

%% local states: lambda_t^2 | ... ~ IG(1, 1/nu_t + (shock_t^2/sigma^2)/(2 s^2 tilde(tau)^2))
shrinkScale     = (s .^ 2) .* globalStatePREV;
this            = 1 ./ localScalePREV + .5 * shocks2 ./ shrinkScale;
localStatePREV  = igamrnd(1, this);
localScalePREV  = igamrnd(1, 1 + 1 ./ localStatePREV);
% note: local*PREV returns NaN for elements where shocks2 has NaN, too

%% global state: tilde(tau)^2 | ... ~ IG((T+1)/2, 1/xi + sum((shock_t^2/sigma^2)/lambda_t^2)/(2 s^2))
this            = 1 ./ globalScalePREV + .5 * sum(shocks2 ./ localStatePREV, dim, 'omitnan') ./ (s .^ 2);
globalStatePREV = igamrnd(Tp1half, this);
globalScalePREV = igamrnd(1, 1 + 1 ./ globalStatePREV);
