function dt = datetimeYYYYQQ(textDates)

dt = cellfun(@(x) datetime(str2double(extractBefore(x, 'Q')), ...
    (str2double(extractAfter(x, 'Q')) - 1) * 3 + 1, 1), ...
    textDates, 'UniformOutput', true);